{
 "title": "Log Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Request",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (RequestPath) (count_over_time({app=~\"api-gateway\"} | json [$__range]))",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  },
  {
   "title": "Agent",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ClientAgent) (count_over_time({app=~\"api-gateway\"} | json [$__range]))",
     "legendFormat": "{{ClientAgent}}"
    }
   ]
  },
  {
   "title": "IP",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ClientIp) (count_over_time({app=~\"api-gateway\"} | json [$__range]))",
     "legendFormat": "{{ClientIp}}"
    }
   ]
  },
  {
   "title": "Agent (BU)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app=~\"api-gateway\"}"
    }
   ]
  }
 ]
}