{
 "title": "General",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "jobs", "label": "app", "query": { "query": "label_values(job)" } },
   { "name": "host", "query": "label_values(host)" },
   { "name": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Apdex",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.256\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1.024\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n)  \n/ 2 / sum(rate(http_request_duration_seconds_count{job=~\"$jobs\", code!~\"101\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code!~\"101\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_working_set_bytes{job=~\"$jobs\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "p95 Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~\"$jobs\", code!=\"101\"}[$interval])) by (le, job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5.*\", job=~\"$jobs\"}[$interval])) by (job)\n/\nsum(rate(http_requests_received_total{code=~\"2.*|3.*|4.*|5.*\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{job=~\"$jobs\"}[$interval])) by (job) / sum(rate(dotnet_threadpool_queue_length_count{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_count_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=~\"$jobs\", host=~\"$host\", env=~\"$env\"}"
    }
   ]
  }
 ]
}