{
 "title": "App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "jobs", "label": "app", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.256\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1.024\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n)  \n/ 2 / sum(rate(http_request_duration_seconds_count{job=~\"$jobs\", code!~\"101\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code!~\"101\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "p95 Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~\"$jobs\", code!=\"101\"}[$interval])) by (le, job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5.*\", job=~\"$jobs\"}[$interval])) by (job)\n/\nsum(rate(http_requests_received_total{code=~\"2.*|3.*|4.*|5.*\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=~\"$jobs\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{job=~\"$jobs\"}[$interval])) by (job) / sum(rate(dotnet_threadpool_queue_length_count{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_working_set_bytes{job=~\"$jobs\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_count_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Paused Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_pause_ratio{job=~\"$jobs\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_total{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Apdex",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.256\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1.024\", job=~\"$jobs\", code!~\"101|5.*\"}[$interval])) by (job)\n)  \n/ 2 / sum(rate(http_request_duration_seconds_count{job=~\"$jobs\", code!~\"101\"}[$interval])) by (job)",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code!~\"101\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5.*\", job=~\"$jobs\"}[$interval])) by (job)\n/\nsum(rate(http_requests_received_total{code=~\"2.*|3.*|4.*|5.*\", job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{code!~\"101\", job=~\"$jobs\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=~\"$jobs\", code!=\"101\"}[$interval])) by (le, job))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=~\"$jobs\", code!=\"101\"}[$interval])) by (le, job))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=~\"$jobs\", code!=\"101\"}[$interval])) by (le, job))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request In Progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{job=~\"$jobs\"}) by (job)",
     "legendFormat": "Request In Progress"
    }
   ]
  },
  { "title": "CPU / Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_num_threads{job=~\"$jobs\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "dotnet_threadpool_num_threads{job=~\"$jobs\"}",
     "legendFormat": "Pool Threads"
    },
    {
     "expr": "dotnet_threadpool_timer_count{job=~\"$jobs\"}",
     "legendFormat": "Timers"
    }
   ]
  },
  {
   "title": "Thread Pool Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{job=~\"$jobs\"}[$interval])) by (job) / sum(rate(dotnet_threadpool_queue_length_count{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "In queue"
    },
    {
     "expr": "sum(rate(dotnet_threadpool_throughput_total{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "Completed"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_memory_total_available_bytes{job=~\"$jobs\"}) by (job)",
     "legendFormat": "Total bytes available"
    },
    {
     "expr": "sum(process_working_set_bytes{job=~\"$jobs\"}) by (job)",
     "legendFormat": "# bytes in physical memory"
    },
    {
     "expr": "sum(dotnet_total_memory_bytes{job=~\"$jobs\"}) by (job)",
     "legendFormat": "Total bytes"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_heap_size_bytes{job=~\"$jobs\"}) by (job, gc_generation)",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_count_total{job=~\"$jobs\"}[$__rate_interval])) by (job, gc_generation)",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC Paused Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_pause_ratio{job=~\"$jobs\"}) by (job)",
     "legendFormat": "% Paused Time for GC"
    }
   ]
  },
  { "title": "Exceptions / JIT / Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_total{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Locks Contended",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_contention_total{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "Locks contended"
    }
   ]
  },
  {
   "title": "JIT Compiled Methods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_jit_method_total{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "JIT Compiled Methods"
    }
   ]
  },
  {
   "title": "JIT Compiled IL Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_jit_il_bytes{job=~\"$jobs\"}[$interval])) by (job)",
     "legendFormat": "JIT Compiled IL Bytes"
    }
   ]
  },
  { "title": "Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "jobs" },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_sockets_bytes_sent_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(increase(dotnet_sockets_bytes_received_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_sockets_connections_established_incoming_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(increase(dotnet_sockets_connections_established_outgoing_total{job=~\"$jobs\"}[$__rate_interval])) by (job)",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}