kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  environment:
    USERNAME:
      from_secret: docker_user
    PASSWORD:
      from_secret: docker_pass
  commands:
  - echo $USERNAME $PASSWORD
  - docker login -u $USERNAME -p $PASSWORD

- name: build
  commands:
  - ./ci/build.sh

# trigger:
#   branch:
  # - staging
