---
kind: pipeline
type: exec
name: build & deploy

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  environment:
    USERNAME:
      from_secret: docker_user
    PASSWORD:
      from_secret: docker_pass
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  when:
    target:
      exclude:
      - production

- name: build
  commands:
  - ./ci/build.sh push
  when:
    target:
      exclude:
      - production

- name: start staging
  environment:
    START_STAGING_CMD:
      from_secret: start_staging_cmd
  commands:
  - eval $START_STAGING_CMD
  when:
    target:
      exclude:
      - production

- name: test
  environment:
    URL:
      from_secret: staging_url
  commands:
  - ./ci/test.sh $URL staging
  when:
    target:
      exclude:
      - production

- name: stop staging
  environment:
    STOP_STAGING_CMD:
      from_secret: stop_staging_cmd
  commands:
  - eval $STOP_STAGING_CMD
  when:
    target:
      exclude:
      - production

- name: deploy prod
  environment:
    DEPLOY_PROD_CMD:
      from_secret: deploy_prod_cmd
  commands:
  - eval $DEPLOY_PROD_CMD
  when:
    target:
    - production

trigger:
  branch:
  - staging
  event:
  - push
