---
kind: pipeline
type: exec
name: build & test

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  environment:
    USERNAME:
      from_secret: docker_user
    PASSWORD:
      from_secret: docker_pass
  commands:
  - docker login -u $USERNAME -p $PASSWORD

- name: build
  commands:
  - ./ci/build.sh push

- name: start staging
  environment:
    START_STAGING_CMD:
      from_secret: start_staging_cmd
  commands:
  - eval $START_STAGING_CMD

- name: test
  environment:
    URL:
      from_secret: staging_url
  commands:
  - ./ci/test.sh $URL staging

- name: stop staging
  environment:
    STOP_STAGING_CMD:
      from_secret: stop_staging_cmd
  commands:
  - eval $STOP_STAGING_CMD

trigger:
  target:
    exclude:
    - production
  branch:
  - adjust-ci
  event:
  - push

---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: deploy prod
  environment:
    DEPLOY_PROD_CMD:
      from_secret: deploy_prod_cmd
  commands:
  - eval $DEPLOY_PROD_CMD
  when:
    target:
    - production

trigger:
  target:
  - production
