---
kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  environment:
    USERNAME:
      from_secret: docker_user
    PASSWORD:
      from_secret: docker_pass
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  when:
    target:
      exclude:
      - production

# - name: build
#   commands:
#   - ./ci/build.sh push

- name: deploy to test
  environment:
    DEPLOY_TEST_CMD:
      from_secret: deploy_test_cmd
  commands:
  - eval $DEPLOY_TEST_CMD
  when:
    target:
      exclude:
      - production

# - name: test
#   environment:
#     URL:
#       from_secret: staging_url
#   commands:
#   - ./ci/test.sh $URL

# - name: deploy to prod
#   environment:
#     DEPLOY_PROD_CMD:
#       from_secret: deploy_prod_cmd
#   commands:
#   - eval $DEPLOY_PROD_CMD
#   when:
#     target:
#     - production

- name: deploy to prod
  environment:
    DEPLOY_PROD_CMD:
      from_secret: deploy_prod_cmd
  commands:
  - eval $DEPLOY_PROD_CMD
  when:
    target:
    - production


- name: deploy to prod
  commands:
  - echo 123123
  when:
    target:
    - production

# trigger:
#   event:
#   - custom
