kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  environment:
    docker_user:
      from_secret: docker_user
    docker_pass:
      from_secret: docker_pass
  commands:
  - echo "$docker_user" "$docker_pass"

- name: build
  commands:
  - ./ci/build.sh

# trigger:
#   branch:
  # - staging
