kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker login
  commands:
  - echo ${docker_user} ${docker_pass}
  - docker login ${docker_user} ${docker_pass}
- name: build
  commands:
  - ./ci/build.sh

# trigger:
#   branch:
  # - staging
