services:
  mongo-db:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db-volume:/data/db
    # restart: unless-stopped
    ports:
      - "27017:27017"

  test-e2e-chrome:
    image: selenium/standalone-chrome:127.0-20240813
    platform: linux/x86_64
    ports:
      - "4444:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # restart: unless-stopped

volumes:
  mongo-db-volume:
