export const TASKS_LOADING = 'TASKS_LOADING'
export type TASKS_LOADING = typeof TASKS_LOADING

export const TASKS_LOADING_SUCCESS = 'TASKS_LOADING_SUCCESS'
export type TASKS_LOADING_SUCCESS = typeof TASKS_LOADING_SUCCESS

export const TASKS_LOADING_FAILED = 'TASKS_LOADING_FAILED'
export type TASKS_LOADING_FAILED = typeof TASKS_LOADING_FAILED

export const TASKS_LOCAL_UPDATE = 'TASKS_LOCAL_UPDATE'
export type TASKS_LOCAL_UPDATE = typeof TASKS_LOCAL_UPDATE
