export const EDITTASK_MODALOPEN = 'EDITTASK_MODALOPEN'
export type EDITTASK_MODALOPEN = typeof EDITTASK_MODALOPEN

export const EDITTASK_TASKMODEL = 'EDITTASK_TASKMODEL'
export type EDITTASK_TASKMODEL = typeof EDITTASK_TASKMODEL
