export const EDITTASK_MODALOPEN = 'EDITTASK_MODALOPEN'
export type EDITTASK_MODALOPEN = typeof EDITTASK_MODALOPEN

export const EDITTASK_TASKMODEL = 'EDITTASK_TASKMODEL'
export type EDITTASK_TASKMODEL = typeof EDITTASK_TASKMODEL

export const EDITTASK_SET_MODEL = 'EDITTASK_SET_MODEL'
export type EDITTASK_SET_MODEL = typeof EDITTASK_SET_MODEL
