export const LOGIN_PROCESSING = 'LOGIN_PROCESSING'
export type LOGIN_PROCESSING = typeof LOGIN_PROCESSING

export const LOGIN_SIGNIN_FINISH = 'LOGIN_SIGNIN_FINISH'
export type LOGIN_SIGNIN_FINISH = typeof LOGIN_SIGNIN_FINISH

export const LOGIN_INITIAL_LOGGING_IN = 'LOGIN_INITIAL_LOGGING_IN'
export type LOGIN_INITIAL_LOGGING_IN = typeof LOGIN_INITIAL_LOGGING_IN
