export const MODALCONFIRM_OPEN = 'MODALCONFIRM_OPEN'
export type MODALCONFIRM_OPEN = typeof MODALCONFIRM_OPEN

export const MODALCONFIRM_CLOSE = 'MODALCONFIRM_CLOSE'
export type MODALCONFIRM_CLOSE = typeof MODALCONFIRM_CLOSE
