import { PlannedRecurrence } from '../../models'

export const RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = 'RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING'
export type RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = typeof RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
export interface ICreateRecurrencesProcessing {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
}

export const RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = 'RECURRENCESVIEW_CREATING_RECURRENCES_FINISH'
export type RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = typeof RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
export interface ICreateRecurrencesFinish {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING = 'RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING'
export type RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING = typeof RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING
export interface ILoadRecurrencesProcessing {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_FAIL = 'RECURRENCESVIEW_LOADING_RECURRENCES_FAIL'
export type RECURRENCESVIEW_LOADING_RECURRENCES_FAIL = typeof RECURRENCESVIEW_LOADING_RECURRENCES_FAIL
export interface ILoadRecurrencesFail {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_FAIL
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS = 'RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS'
export type RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS = typeof RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS
export interface ILoadRecurrencesSuccess {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS
    plannedRecurrences: PlannedRecurrence[]
}

export const RECURRENCESVIEW_CHANGE_EDITTING_RECURRENCE = 'RECURRENCESVIEW_CHANGE_EDITTING_RECURRENCE'
export type RECURRENCESVIEW_CHANGE_EDITTING_RECURRENCE = typeof RECURRENCESVIEW_CHANGE_EDITTING_RECURRENCE
export interface IChangeEdittingRecurrence {
    type: RECURRENCESVIEW_CHANGE_EDITTING_RECURRENCE
    edittingRecurrenceId: number | null
}

export const RECURRENCESVIEW_CHANGE_RECURRENCE = 'RECURRENCESVIEW_CHANGE_RECURRENCE'
export type RECURRENCESVIEW_CHANGE_RECURRENCE = typeof RECURRENCESVIEW_CHANGE_RECURRENCE
export interface IChangeRecurrence {
    type: RECURRENCESVIEW_CHANGE_RECURRENCE
    plannedRecurrence: PlannedRecurrence
}

export const RECURRENCESVIEW_SAVING_PROCESSING = 'RECURRENCESVIEW_SAVING_PROCESSING'
export type RECURRENCESVIEW_SAVING_PROCESSING = typeof RECURRENCESVIEW_SAVING_PROCESSING
export interface ISaveRecurrencesProcessing {
    type: RECURRENCESVIEW_SAVING_PROCESSING
}

export const RECURRENCESVIEW_SAVING_FAIL = 'RECURRENCESVIEW_SAVING_FAIL'
export type RECURRENCESVIEW_SAVING_FAIL = typeof RECURRENCESVIEW_SAVING_FAIL
export interface ISaveRecurrencesFail {
    type: RECURRENCESVIEW_SAVING_FAIL
}

export const RECURRENCESVIEW_SAVING_SUCCESS = 'RECURRENCESVIEW_SAVING_SUCCESS'
export type RECURRENCESVIEW_SAVING_SUCCESS = typeof RECURRENCESVIEW_SAVING_SUCCESS
export interface ISaveRecurrencesSuccess {
    type: RECURRENCESVIEW_SAVING_SUCCESS
}

export const RECURRENCESVIEW_ADD_RECURRENCE = 'RECURRENCESVIEW_ADD_RECURRENCE'
export type RECURRENCESVIEW_ADD_RECURRENCE = typeof RECURRENCESVIEW_ADD_RECURRENCE
export interface IAddRecurrence {
    type: RECURRENCESVIEW_ADD_RECURRENCE
}

export const RECURRENCESVIEW_DELETE_RECURRENCE = 'RECURRENCESVIEW_DELETE_RECURRENCE'
export type RECURRENCESVIEW_DELETE_RECURRENCE = typeof RECURRENCESVIEW_DELETE_RECURRENCE
export interface IDeleteRecurrence {
    type: RECURRENCESVIEW_DELETE_RECURRENCE
    id: number
}

export type RecurrencesViewAction =
    ICreateRecurrencesProcessing |
    ICreateRecurrencesFinish |
    ILoadRecurrencesProcessing |
    ILoadRecurrencesFail |
    ILoadRecurrencesSuccess |
    IChangeEdittingRecurrence |
    IChangeRecurrence |
    ISaveRecurrencesProcessing |
    ISaveRecurrencesFail |
    ISaveRecurrencesSuccess |
    IAddRecurrence |
    IDeleteRecurrence
