import { PlannedRecurrence } from '../../models'

export const RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = 'RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING'
export type RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = typeof RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
export interface ICreateRecurrencesProcessing {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
}

export const RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = 'RECURRENCESVIEW_CREATING_RECURRENCES_FINISH'
export type RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = typeof RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
export interface ICreateRecurrencesFinish {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING = 'RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING'
export type RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING = typeof RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING
export interface ILoadRecurrencesProcessing {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_PROCESSING
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_FAIL = 'RECURRENCESVIEW_LOADING_RECURRENCES_FAIL'
export type RECURRENCESVIEW_LOADING_RECURRENCES_FAIL = typeof RECURRENCESVIEW_LOADING_RECURRENCES_FAIL
export interface ILoadRecurrencesFail {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_FAIL
}

export const RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS = 'RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS'
export type RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS = typeof RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS
export interface ILoadRecurrencesSuccess {
    type: RECURRENCESVIEW_LOADING_RECURRENCES_SUCCESS
    plannedRecurrences: PlannedRecurrence[]
}

export type RecurrencesViewAction =
    ICreateRecurrencesProcessing |
    ICreateRecurrencesFinish |
    ILoadRecurrencesProcessing |
    ILoadRecurrencesFail |
    ILoadRecurrencesSuccess
