export const RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = 'RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING'
export type RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING = typeof RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
export interface ICreateRecurrencesProcessing {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_PROCESSING
}

export const RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = 'RECURRENCESVIEW_CREATING_RECURRENCES_FINISH'
export type RECURRENCESVIEW_CREATING_RECURRENCES_FINISH = typeof RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
export interface ICreateRecurrencesFinish {
    type: RECURRENCESVIEW_CREATING_RECURRENCES_FINISH
}

export type RecurrencesViewAction =
    ICreateRecurrencesProcessing |
    ICreateRecurrencesFinish
