export const SETTINGS_LOAD_PROCESSING = 'SETTINGS_LOAD_PROCESSING'
export type SETTINGS_LOAD_PROCESSING = typeof SETTINGS_LOAD_PROCESSING

export const SETTINGS_LOAD_FINISH = 'SETTINGS_LOAD_FINISH'
export type SETTINGS_LOAD_FINISH = typeof SETTINGS_LOAD_FINISH

export const SETTINGS_SAVE_PROCESSING = 'SETTINGS_SAVE_PROCESSING'
export type SETTINGS_SAVE_PROCESSING = typeof SETTINGS_SAVE_PROCESSING

export const SETTINGS_SAVE_FINISH = 'SETTINGS_SAVE_FINISH'
export type SETTINGS_SAVE_FINISH = typeof SETTINGS_SAVE_FINISH

export const SETTINGS_UPDATE = 'SETTINGS_UPDATE'
export type SETTINGS_UPDATE = typeof SETTINGS_UPDATE
