export const SETTINGS_LOAD_PROCESSING = 'SETTINGS_LOAD_PROCESSING'
export type SETTINGS_LOAD_PROCESSING = typeof SETTINGS_LOAD_PROCESSING

export const SETTINGS_LOAD_SUCCESS = 'SETTINGS_LOAD_SUCCESS'
export type SETTINGS_LOAD_SUCCESS = typeof SETTINGS_LOAD_SUCCESS

export const SETTINGS_LOAD_FAIL = 'SETTINGS_LOAD_FAIL'
export type SETTINGS_LOAD_FAIL = typeof SETTINGS_LOAD_FAIL

export const SETTINGS_SAVE_PROCESSING = 'SETTINGS_SAVE_PROCESSING'
export type SETTINGS_SAVE_PROCESSING = typeof SETTINGS_SAVE_PROCESSING

export const SETTINGS_SAVE_FINISH = 'SETTINGS_SAVE_FINISH'
export type SETTINGS_SAVE_FINISH = typeof SETTINGS_SAVE_FINISH
