version: '3'

services:
  mongo-db:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db-volume:/data/db
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M

  postgres-db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M

  backend:
    build:
      context: ../
      dockerfile: infrastructure/apps/backend.dockerfile
    ports:
      - 5000:5000
    environment:
      - DD_SERVICE_DISCOVERY_HOST=${IP:-backend}
      - DD_SERVICE_DISCOVERY_PORT=5000
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M

  web-client:
    build:
      context: ../
      dockerfile: infrastructure/apps/web-client.dockerfile
    ports:
      - 3000:3000
    environment:
      - DD_SERVICE_DISCOVERY_HOST=${IP:-web-client}
      - DD_SERVICE_DISCOVERY_PORT=3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M

volumes:
  postgres-db-volume:
  mongo-db-volume:
