FROM mcr.microsoft.com/dotnet/sdk:5.0-focal

COPY code/apps/TaskServiceApp /app/code/apps/TaskServiceApp
COPY code/libs/DarkDeeds.Authentication /app/code/libs/DarkDeeds.Authentication
COPY infrastructure/apps/TaskServiceApp/entry.sh /app/code/apps/TaskServiceApp/DarkDeeds.TaskServiceApp/DarkDeeds.TaskServiceApp.App

WORKDIR /app/code/apps/TaskServiceApp/DarkDeeds.TaskServiceApp/DarkDeeds.TaskServiceApp.App

RUN dotnet build

ENTRYPOINT ["/bin/sh", "-c", "./entry.sh"]