FROM mcr.microsoft.com/dotnet/sdk:5.0-focal

COPY code/apps/AuthServiceApp /app/code/apps/AuthServiceApp
COPY code/libs/DarkDeeds.Authentication /app/code/libs/DarkDeeds.Authentication
COPY infrastructure/apps/AuthServiceApp/entry.sh /app/code/apps/AuthServiceApp/DarkDeeds.AuthServiceApp/DarkDeeds.AuthServiceApp.App

WORKDIR /app/code/apps/AuthServiceApp/DarkDeeds.AuthServiceApp/DarkDeeds.AuthServiceApp.App

RUN dotnet build

ENTRYPOINT ["/bin/sh", "-c", "./entry.sh"]