name: Deployment

on:
  workflow_run:
    workflows: ["E2E Testing"]
    types:
      - completed
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    steps:
      - name: Deploy
        run: |
          echo "Deployment triggered"
