name: CI

on: [push]

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 21.x
      uses: actions/setup-node@v1
      with:
        node-version: 21.x
    - name: Build FE-4
      run: |
        cd code/frontend
        npm install
        npm run ci

  build-be:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Build BE
      run: |
        dotnet build -warnaserror code/backend/DarkDeeds.sln
        dotnet test code/backend/DarkDeeds.sln

  build-e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Build E2E Tests
      run: |
        dotnet build -warnaserror code/tests/DarkDeeds.E2eTests/DarkDeeds.E2eTests.sln

  build-load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Build Load Tests
      run: |
        dotnet build -warnaserror code/tests/DarkDeeds.LoadTests/DarkDeeds.LoadTests.sln
