name: CI

on: [push]

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build FE
      run: |
        cd code/frontend/app
        npm install
        npm rebuild node-sass
        npm run build
        npm run test-ci
        cd ../server
        npm install

  build-be:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build BE
      run: |
        dotnet test code/backend/DarkDeeds.ServiceTask.Tests/DarkDeeds.ServiceTask.Tests.csproj
        dotnet test code/backend/DarkDeeds.TelegramClient.Tests/DarkDeeds.TelegramClient.Tests.csproj
        dotnet build code/backend/DarkDeeds.sln

  build-e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build E2E Tests
      run: |
        dotnet build code/tests/DarkDeeds.E2eTests/DarkDeeds.E2eTests.sln

  build-load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Load Tests
      run: |
        dotnet build code/tests/DarkDeeds.LoadTests/DarkDeeds.LoadTests.sln
